name: Daily Vehicle Search

on:
  schedule:
    # Runs at 08:00 AM UTC every day (adjust as needed)
    - cron: '0 8 */3 * *'
  # Allows you to click a button in the GitHub UI to run it manually
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install playwright playwright-stealth beautifulsoup4 lxml pytz
          playwright install chromium

      - name: Run script
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python vehicle_search_automation.py
